### ISSUE TITLE
Potential optimizations have gone mayhem

### ISSUE THREAD

**Issue by theNestruo** [santiontanon/mdlz80optimizer#19] opened 2020-08-11 14:17 UTC
Latest version (0.9) has gone mayhem with the potential optimizations...

Several examples, randomly extracted from the **2195 (!!)** optimizations found:

```
INFO: Potential optimization (Remove unused ld ?reg,?any) in lib/msx/cartridge.asm#37: 	ld	sp, [HIMEM]
(...)
INFO: Pattern-based optimization in lib/msx/cartridge.asm#77: Replace inc l; ... inc l with ld a,l; add a,4; ld l,a (0 bytes, 2 t-states saved)
INFO: Potential optimization (Remove unused ld ?reg,?any) in lib/msx/cartridge.asm#80: 	inc	l
INFO: Potential optimization (Remove unused ld ?reg,?any) in lib/msx/cartridge.asm#80: 	inc	l
(...)
INFO: Potential optimization (Remove unused ld ?reg,?any) in games/stevedore/stevedore.code.asm#3121: 	ld	hl, JIFFY
INFO: Potential optimization (Replace ld ?regpair,?const1 with ld ?regpairl,(?const1 % 256)) in games/stevedore/stevedore.code.asm#3121: 	ld	hl, JIFFY
INFO: Potential optimization (Replace ld ?regpair,?const1 with ld ?regpairh,(?const1) >> 8) in games/stevedore/stevedore.code.asm#3121: 	ld	hl, JIFFY
(...)
INFO: PatternBasedOptimizer: 17 patterns applied, 16 bytes, 60 t-states saved.
```

Obviously, `SP` is being used, `inc l` is not a "unused `ld ?reg,?any`", and that `ld hl, JIFFY` is followed `ld a, [hl]`...

It seems to be failing to detect any register usage, or losing track of the current line when evaluating usage.

**Comment by santiontanon** [comment] 2020-08-11 15:59
Hmm, weird! I cannot reproduce it though. I have just tried with the 19 projects I use for testing, and it is obtaining the expected set of optimizations for all projects. Is this with the 0.9 release version, or with the latest version in the repo? If you are using the version in the repo, can you run the unit tests in your end, just to make sure nothing went weird with the code base on your copy?

**Comment by santiontanon** [comment] 2020-08-11 16:49
But looking at the output you show above, it looks like the parser went crazy! haha 

Let me know if you have a chance to just run the unit tests and see if that gives us some hints. Thanks again for reporting! :)

**Comment by theNestruo** [comment] 2020-08-11 17:33
Latest from repository. Tests (`mvn test`) succeed.

Using this file (code is nonsense; just contains some excerpts from [MSXlib cartridge.asm](https://github.com/theNestruo/msx-msxlib/blob/master/lib/msx/cartridge.asm)):

```
	EXPTBL:	equ $fcc1
	org	$4000
	ld	hl, EXPTBL
	inc	l
	inc	l
	inc	l
	inc	l
	ld	a, [hl]
	push	af
	inc	sp
```

I've been able to reproduce the error:
```
>mdlz80 -dialect tniasm -po -popotential dummy.asm
INFO: Potential optimization (Remove unused ld ?reg,?any) in dummy.asm#3:       ld      hl, EXPTBL
INFO: Potential optimization (Replace ld ?regpair,?const1 with ld ?regpairl,(?const1 % 256)) in dummy.asm#3:    ld      hl, EXPTBL
INFO: Potential optimization (Replace ld ?regpair,?const1 with ld ?regpairh,(?const1) >> 8) in dummy.asm#3:     ld      hl, EXPTBL
INFO: Pattern-based optimization in dummy.asm#4: Replace inc l; ... inc l with ld a,l; add a,4; ld l,a (0 bytes, 2 t-states saved)
INFO: Potential optimization (Remove unused ld ?reg,?any) in dummy.asm#7:       inc     l
INFO: Potential optimization (Remove unused ld ?reg,?any) in dummy.asm#7:       inc     l
INFO: Potential optimization (Remove unused ld ?reg,?any) in dummy.asm#8:       ld      a, [hl]
INFO: PatternBasedOptimizer: 1 patterns applied, 0 bytes, 2 t-states saved.
```

**Comment by santiontanon** [comment] 2020-08-11 17:42
Oh! interesting! I'll check that in my lunch break. Thanks a lot theNestruo!!

**Comment by santiontanon** [comment] 2020-08-11 17:50
But wait, I see, I missed the "potential optimization" part in your original message! I do not have any tests for that part, so, I see it could have been broken. In that case, after I fix it, I need to add unit tests for that functionality, to make sure it does not get broken again :)

**Comment by santiontanon** [comment] 2020-08-12 06:25
Alright, I just pushed a fix! I had completely forgotten about that feature, so apologies for breaking it haha.

I had implemented this as "also printing optimizations that violate constraints". However, as the number of patterns grew and they became more flexible with more and more constraints, this caused a lot of false alarms. I updated the reporting code, and also made it only show those patterns that the optimizer is really not sure, which was the original intended behavior.

I haven't tested it much as I only had 30mins of time to work on MDL today, but it should work better now at least! :)

**Comment by theNestruo** [comment] 2020-08-12 14:14
It behaves much better now, thanks!!!

It seems that, at least in my code, most of the potential optimizations are related to BIOS calls: MDL cannot detect register usage within the BIOS routine (it doesn't have the code), hence considers the load useless. That's expected.
That happens also after a `jp (hl)`, `jp (ix)` or `jp (iy)`. Again, that's expected. However, it is suggesting to "Remove unused ld ix,UPDATE_PLAYER_ANIMATION_CONDITIONAL" (probably due misconfiguration detecting IX usage in `jp (ix)`?).

Also, some weird optimizations. For example, these single `inc`s:

```
INFO: Potential optimization (Replace inc c; ... inc c with ld a,c; add a,1; ld c,a) in lib/msx/io/keyboard.asm#54:     inc     c
(...)
INFO: Potential optimization (Replace inc c; ... inc c with ld a,c; add a,1; ld c,a) in lib/msx/etc/msx2_palette.asm#24:        inc     c
(...)
INFO: Potential optimization (Replace inc b; ... inc b with ld a,b; add a,1; ld b,a) in lib/msx/etc/spriteables.asm#228:        inc     b
```

And, related to the useless loads, it seems that 16bit useless loads trigger three optimizations instead of the first one only:

```
INFO: Potential optimization (Remove unused ld bc,8) in lib/msx/io/vram.asm#24:         ld      bc, 8 ; 8b
INFO: Potential optimization (Replace ld bc,8 with ld c,(8 % 256)) in lib/msx/io/vram.asm#24:   ld      bc, 8 ; 8b
INFO: Potential optimization (Replace ld bc,8 with ld b,(8) >> 8) in lib/msx/io/vram.asm#24:    ld      bc, 8 ; 8b
(...)
INFO: Potential optimization (Remove unused ld de,CHRTBL) in lib/msx/io/vram.asm#69:    ld      de, CHRTBL
INFO: Potential optimization (Replace ld de,CHRTBL with ld e,(CHRTBL % 256)) in lib/msx/io/vram.asm#69:         ld      de, CHRTBL
INFO: Potential optimization (Replace ld de,CHRTBL with ld d,(CHRTBL) >> 8) in lib/msx/io/vram.asm#69:  ld      de, CHRTBL
```

But please do not prioritize this issue! These are minor annoyances and I'm just writing them down for the record.

**Comment by santiontanon** [comment] 2020-08-12 17:50
Oh, no problem about prioritizing or not haha. I just add these to my to do list, and when I get to work on MDL, I look to see which is the to-do item that I feel like working on next. But I like fixing these issues, since some times they hint at deeper hidden problems. So, I like to look into them at least to see why are they happening :)

**Comment by santiontanon** [comment] 2020-08-16 06:16
I think the first one should be solved now. But the second case (those 3 optimizations appearing together) is trickier, as all 3 are really potential optimizations. What I was thinking is to only generate one potential optimization per assembler line by default (allow for printing all if desired). What do you think? Patterns in the pattern base are more or less sorted by priority already, so, the first optimization that matches should be the best one in any case.

**Comment by theNestruo** [comment] 2020-08-16 07:16
One potential optimization per line sounds good to me!

**Comment by santiontanon** [comment] 2020-08-16 07:46
alright! done! I'll close the issue tentatively (but please reopen if it doesn't work as expected! :) )

**Closed by santiontanon** 2020-08-16 07:46 UTC
